# Generated by Django 6.0.3 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_steps_recipe_instructions_remove_recipe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
