# Generated by Django 6.0.3 on 2026-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
