# Generated by Django 6.0.3 on 2026-04-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='recipes.recipe'),
        ),
    ]
